server:
  port: 8081
spring:
  datasource:
#    url: jdbc:mysql://education-platform-db.ca9espjthsfo.eu-central-1.rds.amazonaws.com:3306/education_platform_db?createDatabaseIfNotExist=true
    url: jdbc:mysql://localhost:3306/education_platform_db?createDatabaseIfNotExist=true
    username: root
    password: root123!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
